services:
  frontend:
    build: Ui/
    depends_on:
      backend:
        condition: service_started
    restart: always
    volumes:
      - '../Travel_Buddy:/home'  
    ports:
      - 3000:3000

  backend:
    build: Webserver/
    container_name: docker-backend-1
    depends_on:
      database:
        condition: service_healthy
    restart: always
    volumes:
      - '../Travel_Buddy:/home'  
      - './Travel_Buddy/gradlew:/home/gradlew'
    ports:
      - 8080:8080

  database:
    build: Database/
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 10
    restart: always
    ports:
      - 5432:5432
