services:
  nginx:
    image: nginx:latest
    volumes:
      - './Nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  frontend:
    build: Ui/
    depends_on:
      backend:
        condition: service_started
    restart: always
    volumes:
      - '../Travel_Buddy:/home'  
    ports:
      - 3000:3000

  backend:
    build: Webserver/
    container_name: docker-backend-1
    depends_on:
      database:
        condition: service_healthy
    restart: always
    volumes:
      - '../Travel_Buddy:/home'  
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  database:
    build: Database/
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 10
    restart: always
    ports:
      - 5432:5432
