services:

  frontend:
    build: Ui/
    depends_on:
      backend:
        condition: service_started
        restart: true
    volumes:
      - '../Travel_Buddy:/home'  
    ports:
      - 3000:3000

  backend:
    build: Webserver/
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - '../Travel_Buddy:/home'  
    ports:
      - 8080:8080

  database:
    build: Database/
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - 5432:5432
