services:
  backend:
    build: Webserver/
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - '../Travel_Buddy:/home'  

  database:
    build: Database/
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 10

