name: Semgrep Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run Semgrep analysis
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"            # Automatically detects relevant rules
          include: "**/*"           # Scan all files in the repository
          baseline-ref: ""          # Force Semgrep to ignore the baseline
          disable-gitignore: true   # Ensure no files are excluded
          scan-all: true            # Explicitly enable full repository scan
