name: Semgrep Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for full repository scan

      # Step 2: Debug: List all files
      - name: Debug: List all files
        run: ls -R .

      # Step 3: Install Semgrep manually
      - name: Install Semgrep
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install semgrep

      # Step 4: Run Semgrep manually
      - name: Run Semgrep
        run: |
          semgrep --config=auto --include="**/*" --no-git-ignore --error
