# .github/workflows/docker-gradle-test.yml
name: Dockerized Gradle Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Containers
      run: docker-compose -f Docker/docker-compose.yml build

    - name: Start Containers
      run: docker-compose -f Docker/docker-compose.yml up -d

    - name: Run Gradle Tests in Backend Container
      run: docker exec -it docker-backend-1 /bin/sh ./gradlew test

    - name: Tear Down Containers
      if: always()
      run: docker-compose -f Docker/docker-compose.yml down
