# .github/workflows/docker-gradle-test.yml
name: Dockerized Gradle Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Containers
      run: docker-compose -f Docker/docker-compose.yml build

    - name: Start Containers
      run: docker-compose -f Docker/docker-compose.yml up -d

    - name: Run Gradle Tests and Generate Coverage Report
      run: docker exec -i docker-backend-1 ./gradlew test jacocoTestReport

    - name: Verify Files in Container Before Copy
      run: docker exec -i docker-backend-1 ls -la /home/build/reports/jacoco/test/html

    - name: Copy Jacoco Coverage Report to Host
      run: |
        docker cp docker-backend-1:/home/build/reports/jacoco/test/html ./coverage-report

    - name: Upload Coverage Report as Artifact
      uses: actions/upload-artifact@v4s
      with:
        name: jacoco-coverage-report
        path: ./coverage-report/

    - name: Copy Test Report to Host
      run: |
        docker cp docker-backend-1:/home/build/reports/tests/test/ ./test-report

    - name: Upload Test Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: ./test-report/
        
    - name: Verify Files in Container
      run: docker exec -i docker-backend-1 ls -la /home

    - name: Verify Coverage Report Files
      run: ls -la ./coverage-report

    - name: Run Gradle Tests
      run: docker exec -i docker-backend-1 ./gradlew test

    - name: Tear Down Containers
      if: always()
      run: docker-compose -f Docker/docker-compose.yml down