# .github/workflows/docker-gradle-test.yml
name: Dockerized Gradle Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Clean Docker Environment
      run: docker system prune -a -f

    - name: Rebuild Docker Images
      run: docker-compose -f Docker/docker-compose.yml build --no-cache

    - name: Start Containers
      run: docker-compose -f Docker/docker-compose.yml up -d

    - name: Wait for Backend to be Healthy
      run: |
        for i in {1..30}; do
          STATUS=$(docker inspect --format='{{.State.Health.Status}}' docker-backend-1 || echo "not found")
          echo "Backend status: $STATUS"
          if [ "$STATUS" == "healthy" ]; then
            echo "Backend is healthy!"
            exit 0
          fi
          sleep 5
        done
        echo "Backend did not become healthy in time."
        exit 1

    - name: Run Gradle Tests and Generate Coverage Report
      run: docker exec -i docker-backend-1 ./gradlew test jacocoTestReport

    - name: Verify Files in Container Before Copy
      run: docker exec -i docker-backend-1 ls -la /home/build/reports/jacoco/test/html

    - name: Copy Jacoco Coverage Report to Host
      run: |
        docker cp docker-backend-1:/home/build/reports/jacoco/test/html ./coverage-report

    - name: Upload Coverage Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-coverage-report
        path: ./coverage-report/

    - name: Copy Test Report to Host
      run: |
        docker cp docker-backend-1:/home/build/reports/tests/test/ ./test-report

    - name: Upload Test Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: ./test-report/
        
    - name: Verify Files in Container
      run: docker exec -i docker-backend-1 ls -la /home

    - name: Verify Coverage Report Files
      run: ls -la ./coverage-report

    - name: Run Gradle Tests
      run: docker exec -i docker-backend-1 ./gradlew test

    - name: Tear Down Containers
      if: always()
      run: docker-compose -f Docker/docker-compose.yml down